<?xml version="1.0" encoding="utf-8"?><Database Name="DB_9CA56F_AskIT" Class="DataBaseClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SQL5012.Smarterasp.net;Initial Catalog=DB_9CA56F_AskIT;Persist Security Info=True;User ID=DB_9CA56F_AskIT_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_9CA56F_AskITConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Area" Member="Area">
    <Type Name="Area">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AreaName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Area_UserToArea" Member="UserToArea" ThisKey="ID" OtherKey="areaID" Type="UserToArea" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Room">
    <Type Name="Room">
      <Column Name="AuthorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Room_RoomToID" Member="RoomToID" ThisKey="ID" OtherKey="roomID" Type="RoomToID" />
      <Association Name="Users_Room" Member="Users" ThisKey="AuthorID" OtherKey="ID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoomToID" Member="RoomToID">
    <Type Name="RoomToID">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_RoomToID" Member="Room" ThisKey="roomID" OtherKey="ID" Type="Room" IsForeignKey="true" />
      <Association Name="Users_RoomToID" Member="Users" ThisKey="userID" OtherKey="ID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[E-Mail]" Member="E_Mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Knowledge" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Users_Room" Member="Room" ThisKey="ID" OtherKey="AuthorID" Type="Room" />
      <Association Name="Users_RoomToID" Member="RoomToID" ThisKey="ID" OtherKey="userID" Type="RoomToID" />
      <Association Name="Users_UserToArea" Member="UserToArea" ThisKey="ID" OtherKey="userID" Type="UserToArea" />
    </Type>
  </Table>
  <Table Name="dbo.UserToArea" Member="UserToArea">
    <Type Name="UserToArea">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="areaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Area_UserToArea" Member="Area" ThisKey="areaID" OtherKey="ID" Type="Area" IsForeignKey="true" />
      <Association Name="Users_UserToArea" Member="Users" ThisKey="userID" OtherKey="ID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
</Database>